spring:
  datasource:
    url: jdbc:mysql://api.prism-sfa-dev.net:3306/sfa_db
    username: PrismSfa
    password: TestUser123!
    hikari:
      connection-timeout: 60000          # 1 minute
      max-lifetime: 1800000              # 30 minutes
      idle-timeout: 300000               # 5 minutes
      maximum-pool-size: 10              # Adjust based on application needs

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  spring:
    security:
      enabled: false
  application:
    name: inventory-service
product:
  getProduct:
    url: http://localhost:9093/product-service/products/
clients:
  service:
    url: http://localhost:8080/client-fmcg/getClientFMCGById
server:
  port: 9095
  servlet:
    context-path: /inventory-service

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

application:
  config:
    trace: true
  spring:
    mvc:
      cors:
        allowed-origins: "*"
        allowed-methods: GET,POST,PUT,DELETE
        allowed-headers: "*"
        allow-credentials: true