spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventoryDb
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  spring:
    security:
      enabled: false
  application:
    name: inventory-service

server:
  port: 9095
  servlet:
    context-path: /inventory-service

application:
  config:
    trace: true
validate:
  token:
    url: http://localhost:9094/auth-service/auth/validateToken?token=