name: Deploy Inventory Service to VPS

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      USERNAME: ${{ secrets.USERNAME }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print working directory
        run: |
          pwd
          ls -la

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Inventory Service (Maven)
        run: mvn clean package -DskipTests

      - name: List built artifacts
        run: ls -la target/

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar-file
          path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: jar-file
          path: jar-file/

      - name: Deploy JAR to VPS
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: "jar-file/*.jar"
          target: "~/sfa-service/inventory-service/"

      - name: Remove Old JAR and Deploy New One
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd ~/sfa-service/inventory-service/
            echo "Removing old JAR..."
            rm -f *.jar
            echo "Moving new JAR..."
            mv ~/sfa-service/inventory-service/jar-file/*.jar ~/sfa-service/inventory-service/
            rm -rf ~/sfa-service/inventory-service/jar-file/

      - name: Run Deployment Script on VPS
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd ~/sfa-service/inventory-service/
            PID=$(sudo lsof -n -i:9095 | awk 'NR==2 {print $2}')
            if [ -n "$PID" ]; then
              sudo kill -9 $PID
            fi
            chmod +x inventoryStartUp.sh
            ./inventoryStartUp.sh
            echo "Service started"
      
            
            
