- name: Run Deployment Script on VPS
  uses: appleboy/ssh-action@v0.1.0
  with:
    host: ${{ secrets.VPS_HOST }}
    username: ${{ secrets.VPS_USER }}
    password: ${{ secrets.VPS_PASSWORD }}
    script: |
      cd ~/sfa-service/inventory-service/

      echo "Checking if service is running..."
      PID=$(sudo lsof -n -i:9095 | awk 'NR==2 {print $2}')
      if [ -n "$PID" ]; then
        echo "Killing running service with PID: $PID"
        sudo kill -9 $PID
      else
        echo "No service running on port 9095"
      fi

      echo "Setting execution permission..."
      export JAVA_HOME=/usr/local/java/jdk-17.0.12
      export PATH=$JAVA_HOME/bin:$PATH
      chmod +x inventoryStartUp.sh

      echo "Removing old nohup.out..."
      rm -f nohup.out

      echo "Starting the service using nohup (logs will go to nohup.out)..."
      nohup ./inventoryStartUp.sh &

      echo "Waiting for service startup logs..."
      sleep 5  # allow some time for log to appear
      tail -n 50 -f nohup.out | while read LINE; do
        echo "$LINE"
        if [[ "$LINE" == *"Tomcat started on port 9095 (http) with context path '/inventory-service'"* ]]; then
          echo "Detected Tomcat startup, stopping log streaming."
          pkill -P $$ tail
        fi
      done

      echo "Deployment successful!"
